###

// 我的 Authorization Key(Open API 授權金鑰):
// 台北(中正區) - { stationId: 466920 }
// 新北(板橋) - { stationId: 466880 }
// 桃園(新屋) - { stationId: 467050 }

// fetch all weather from DB
// e.g. `/:apiKey`
GET http://localhost:3000/fetchWeather/<Your Authorization Key>

###

// fetch and save all weather data into MongoDB
// eg. `/fetch/:apiKey`
GET http://localhost:3000/fetchWeather/fetch-and-save/<Your Authorization Key>

###

// fetch a specific city weather data by its stationId
// e.g. `/:apiKey/:stationId`
GET http://localhost:3000/fetchWeather/<Your Authorization Key>/<stationId>

###

// Delete all documents in the `weathers` collection
// e.g. `/:apiKey`
DELETE http://localhost:3000/fetchWeather/<Your Authorization Key>

###
